### ISSUE TITLE
Preflight OPTIONS request should respond with StatusNoContent(204) and not StatusOK(200)

### ISSUE THREAD

**Issue by jeevankk** [go-chi/cors#1]

**Comment by VojtechVitek** [comment]
Can you provide us with a link to the RFC mentioning this?

**Comment by nicksrandall** [comment]
https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

Section 9.2 about OPTIONS method specifically states that response SHOULD be a 200. 

#7 Should make this more explicit.
