### ISSUE TITLE
Handler: Actual request If no Origin present allows the call to complete without validating the origin.

### ISSUE THREAD

**Issue by ahamansh** [go-chi/cors#10]
Scenario:
Added AllowOriginFunc: to validate custom domain.

If curl with -H "Origin: somthing" :::: This call is allowed and the origin validator func is called but not honored.

Call to validate the origin is present in handleActualRequest(); however when a curl request is sent with origin in header it simply allows the call to complete. Should it stop when AllowOriginFunc returns false ???

**Comment by ahamansh** [comment]
Also for the service chaining if we want to validate the origin.

**Comment by pkieltyka** [comment]
Correct, "false" would not set appropriate headers to allow the CORS request to succeed.
