### ISSUE TITLE
Custom header with undercore is been normilize to a header without it

### ISSUE THREAD

**Issue by ocalvet** [go-chi/cors#14]
When I configure the allow headers to the following:

```
AllowedHeaders:   []string{"Accept", "Authorization", "Content-Type", "X-CSRF-Token", "contact_id"},
```

Then I send a request from my react client using the contact_id header on the request I get the following error in the debug log:

```
Preflight aborted: headers '[Contactid]' not allowed
```

When I check the code it looks like parseHeaderList function in the utils.go file is removing the underscores from the header list.  

Why is this the default behavior?

**Comment by Ariel-dono** [comment]
Hello everyone!! Just as @ocalvet says, I found something similar at rs/cors dependency!! 

https://github.com/rs/cors/issues/99

**Comment by Ariel-dono** [comment]
https://httpwg.org/specs/rfc7230.html#rule.token.separators

**Comment by Ariel-dono** [comment]
You even could replace 
https://github.com/rs/cors/blob/d4dacab0671f9aedbf3924d3df2a4a95c8c11a87/utils.go#L28
by 
`func parseHeaderList(headerList string) []string {
	regex := regexp.MustCompile(`[()\[\]/:;<=>?@\\{}]+`)
	headerList = regex.ReplaceAllString(headerList, "")
	return strings.Split(headerList, ",")
}`

**Comment by Ariel-dono** [comment]
https://github.com/rs/cors/pull/103

**Comment by ted-marozzi** [comment]
This should be fixed now for those from the future

**Comment by pkieltyka** [comment]
Thanks for the fix Ted
