### ISSUE TITLE
License

### ISSUE THREAD

**Issue by explodingcamera** [go-chi/cors#3]
Hi, I love chi and would like to keep using this middleware, however I can't because it doesn't have a license.
Would you mind maybe adding something like a MIT license to this repo?

**Comment by VojtechVitek** [comment]
@explodingcamera sure, create a PR with a LICENSE file matching `go-chi/go` and I'm sure we can merge. Thanks

**Comment by rs** [comment]
Speaking of license, this project is a fork of github.com/rs/cors and removed the original license. You might have missed the part of the original license that says:

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```

I also don't really understand why you forked the project instead of submitting a PR, but well…

**Comment by VojtechVitek** [comment]
@explodingcamera @rs thanks for pointing this out.

Resolved in #4 and e87e85b7b5908ec18b4e1ea2958f0f23b0b5b49f.

**Comment by VojtechVitek** [comment]
@rs I'm not sure to be honest. Probably some middleware specific code?

I'll diff the source codes and let you know.

**Comment by rs** [comment]
I looked at the diff and the only noticeable difference is the passing of the request in the `AllowOriginFunc` parameter, which 1/ should not make the original library more or less compatible with chi middleware construct, and 2/ is a feature that could have been discussed for addition in the main library.

**Comment by rs** [comment]
Just added a chi integration example: https://github.com/rs/cors/commit/02026070ea746d775e2d8dfe1efbea899a42f322. It works out of the box.

**Comment by VojtechVitek** [comment]
Yeah, looks like

```diff
- AllowOriginFunc func(origin string) bool
+ AllowOriginFunc func(r *http.Request, origin string) bool
```

is the only major API change. Alongside with some clean-up of Negroni and Martini interfaces, which we've never intended to use.

Let me have a look at the API change a bit deeper.

**Comment by rs** [comment]
We can introduce a new option with the added param. I think it is useful addition.

**Comment by VojtechVitek** [comment]
@rs `AllowOriginRequestFunc` ?

**Comment by rs** [comment]
Yes, something like that

**Comment by jub0bs** [comment]
Related: https://github.com/rs/cors/issues/157
